/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Rising surface layers (elevation via surface color)
        surface: {
          canvas: 'var(--surface-canvas)',
          base: 'var(--surface-base)',
          subtle: 'var(--surface-subtle)',
          DEFAULT: 'var(--surface-surface)',
          raised: 'var(--surface-raised)',
          overlay: 'var(--surface-overlay)',
          inset: 'var(--surface-inset)',
          hover: 'var(--surface-hover)',
          active: 'var(--surface-active)',
          selected: 'var(--surface-selected)',
        },
        // Text hierarchy (mapped as `content`)
        content: {
          DEFAULT: 'var(--content-primary)',
          secondary: 'var(--content-secondary)',
          tertiary: 'var(--content-tertiary)',
          disabled: 'var(--content-disabled)',
          inverse: 'var(--content-inverse)',
          'on-accent': 'var(--content-on-accent)',
          link: 'var(--content-link)',
        },
        // Borders (mapped as `line`)
        line: {
          subtle: 'var(--line-subtle)',
          DEFAULT: 'var(--line-default)',
          strong: 'var(--line-strong)',
          focus: 'var(--line-focus)',
        },
        accent: {
          DEFAULT: 'var(--accent-solid)',
          hover: 'var(--accent-solid-hover)',
          active: 'var(--accent-solid-active)',
          soft: 'var(--accent-soft)',
          'soft-hover': 'var(--accent-soft-hover)',
          text: 'var(--accent-text)',
          ring: 'var(--accent-ring)',
          glow: 'var(--accent-glow)',
        },
        success: { DEFAULT: 'var(--status-success)', soft: 'var(--status-success-soft)' },
        warning: { DEFAULT: 'var(--status-warning)', soft: 'var(--status-warning-soft)' },
        danger: { DEFAULT: 'var(--status-danger)', soft: 'var(--status-danger-soft)' },
        info: { DEFAULT: 'var(--status-info)', soft: 'var(--status-info-soft)' },
        ai: {
          aura: 'var(--ai-aura)',
          'aura-soft': 'var(--ai-aura-soft)',
          listening: 'var(--ai-listening)',
          thinking: 'var(--ai-thinking)',
          speaking: 'var(--ai-speaking)',
        },
      },
      borderColor: {
        DEFAULT: 'var(--line-default)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
      },
      boxShadow: {
        e1: 'var(--elevation-1)',
        e2: 'var(--elevation-2)',
        e3: 'var(--elevation-3)',
        e4: 'var(--elevation-4)',
        'glow-sm': 'var(--glow-sm)',
        'glow-md': 'var(--glow-md)',
        'glow-lg': 'var(--glow-lg)',
        'inner-top': 'var(--inner-top)',
      },
      backdropBlur: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        display: 'var(--font-display)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-lg': ['38px', { lineHeight: '1.08', letterSpacing: '-0.03em', fontWeight: '600' }],
        'display-md': ['30px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        h1: ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['20px', { lineHeight: '1.25', letterSpacing: '-0.015em', fontWeight: '600' }],
        h3: ['17px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.55' }],
        body: ['14px', { lineHeight: '1.55' }],
        'body-sm': ['13px', { lineHeight: '1.5' }],
        label: ['13px', { lineHeight: '1.3', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '1.35', fontWeight: '500' }],
        overline: ['11px', { lineHeight: '1.3', letterSpacing: '0.06em', fontWeight: '600' }],
      },
      spacing: {
        rail: 'var(--layout-sidebar-rail)',
        sidebar: 'var(--layout-sidebar)',
        topbar: 'var(--layout-topbar)',
        statusbar: 'var(--layout-statusbar)',
      },
      zIndex: {
        sticky: '100',
        sidebar: '200',
        topbar: '210',
        dropdown: '300',
        popover: '400',
        tooltip: '500',
        drawer: '600',
        modal: '700',
        palette: '800',
        toast: '900',
        voice: '950',
      },
      transitionTimingFunction: {
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        decelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
        accelerate: 'cubic-bezier(0.3, 0, 1, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        instant: '80ms',
        fast: '140ms',
        base: '220ms',
        slow: '320ms',
        slower: '480ms',
      },
      keyframes: {
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-out': {
          from: { opacity: '1', transform: 'translateY(0)' },
          to: { opacity: '0', transform: 'translateY(4px)' },
        },
        'scale-in': {
          from: { opacity: '0', transform: 'scale(0.97)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'slide-in-left': {
          from: { transform: 'translateX(-100%)' },
          to: { transform: 'translateX(0)' },
        },
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
        breathe: {
          '0%, 100%': { opacity: '0.55', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.04)' },
        },
        'ring-pulse': {
          '0%': { opacity: '0.7', transform: 'scale(0.8)' },
          '100%': { opacity: '0', transform: 'scale(1.9)' },
        },
        spin: {
          to: { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 220ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'scale-in': 'scale-in 220ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'slide-in-right': 'slide-in-right 320ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        'slide-in-left': 'slide-in-left 320ms cubic-bezier(0.05, 0.7, 0.1, 1)',
        shimmer: 'shimmer 1.8s infinite',
        breathe: 'breathe 3s ease-in-out infinite',
        'ring-pulse': 'ring-pulse 2.4s ease-out infinite',
        spin: 'spin 0.7s linear infinite',
      },
    },
  },
  plugins: [],
};
